ansible_ssh_port: 22
ansible_ssh_user: servidorlinux
ansible_ssh_pass: aluno
ansible_become: yes
ansible_become_method: su
ansible_become_user: root
ansible_become_pass: aluno
ansible_connection: ssh 

############################################# SSL CERTIFICATE #############################################

# SSL PADRAO

SSL_CERTIFICATE_TCC_COM: /etc/nginx/ssl/tcc.com.crt  
SSL_CERTIFICATE_KEY_TCC_COM: /etc/nginx/ssl/tcc.com.key


############################################################################################################
