---

TEMPLATE_NGINX: all_nginx.j2
TEMPLATE_CONFD: react_confd.j2
PATH: /home/aluno/
APPLICATION_ENV_PRODUCTION: production
PHP_SOCK: /var/run/php-fpm/www.sock #FC3 SOCK
CONFIG_PRODUCTION:
# FATEC #############################################################
  - NAME: 99-fatec.tcc.com
    CONFIG_PRODUCTION: fatec.tcc.com
    SSL_CERTIFICATE: "{{ SSL_CERTIFICATE_TCC_COM_FC }}"
    SSL_CERTIFICATE_KEY: "{{ SSL_CERTIFICATE_KEY_TCC_COM_FC }}"


INSTRUCTION:
  - env_react
  - react
 